server:
  port: 8080

spring:
  application:
    name: accenture-assessment
  datasource:
    url: jdbc:mysql://localhost:3306/accenture_assessment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        legacy_limit_handler: true
        dialect: org.hibernate.dialect.MySQL55Dialect
        jdbc:
          time_zone: Asia/Jakarta
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  redis:
#    host: localhost
#    port: 6379